# NumPy

Numpy (http://www.numpy.org/) is one of the most useful Python packages and it represents one of the core libraries for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with it. Inside a Python script, everything starts with an import statement:

In [1]:
import numpy as np # everything inside numpy now can be invoked as np.something

## NumPy Arrays

A numpy array is a grid of values. Differently from Python lists, values must to be all of the same type. The number of dimensions is the rank of the array, while the shape of an array is a tuple of integers giving the size of the array along each dimension.

### Array creation

We can initialize numpy arrays from nested Python lists, and access elements using square brackets `[ ]`:

In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array
b = np.array([[1, 2, 3],[4, 5, 6]])   # Create a rank 2 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints a Tuple (note round parenthesis) with one element, the length of the array
print(b.shape)            # Prints a Tuple (note round parenthesis) with one element, the length of the array
print(a[0], a[1], a[2])   
a[0] = 5                  # Change an element of the array
print(a)

print("\n")
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints a Tuple with two elements, the length along each axis
print(b[0, 0], b[0, 1], b[1, 0])
print(b[1,1])

<class 'numpy.ndarray'>
(3,)
(2, 3)
1 2 3
[5 2 3]


(2, 3)
1 2 4
5


Indexing can also be achieved with single `[ ]` for each dimension:

In [3]:
print(b[0][0], b[0][1], b[1][0])

1 2 4


NumPy has many functions for array creation (note the brackets used as argument of function call, indexing uses Tuples or Lists!). See here for full details https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.array-creation.html

In [4]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a,"\n")              

b = np.ones(2)    # Create an array of all ones
print(b,"\n")              

c = np.full([2,2], 7)  # Create an array filled with the given value
print(c,"\n")               

d = np.eye(2)         # Create a 2x2 identity matrix
print(d,"\n")

e = np.arange(3,5,0.5) # Create an array containing numbers between 3 and 5, separated by 0.5
print(e,"\n")

f = np.linspace(3,5,6) # Create an array containing 6 linearly spaced numbers between 3 and 5
print(f,"\n")

g = np.logspace(2,5,4) # Create an array containing 4 log-spaced numbers between 10**2 and 10**5
print(g,"\n")

h = 3**np.arange(2,6,1)
print(h)

i = 10**np.linspace(2,5,4)
print(i)

[[0. 0.]
 [0. 0.]] 

[1. 1.] 

[[7 7]
 [7 7]] 

[[1. 0.]
 [0. 1.]] 

[3.  3.5 4.  4.5] 

[3.  3.4 3.8 4.2 4.6 5. ] 

[   100.   1000.  10000. 100000.] 

[  9  27  81 243]
[   100.   1000.  10000. 100000.]


### Array indexing: slicing

Slicing is a quick method to extract parts of an array. For multidimensional objects, you must specify a slice for each dimension of the array. Slices are specified by the starting index (included), final index (not included) and increment step, i.e. `a[i:j:step]`, all being optional.

In [5]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("tha shape of a:",a.shape)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
print(a)
b = a[:2, 1:3]
print(b,"\n")

tha shape of a: (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]] 



The `ravel()` method can be used to flatten an array (turn it one-dimensional)

In [6]:
a_flat = a.ravel()
print(a_flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Negative numbers can be used to access elements backwards, starting from the end of the array. For example, `a_flat[-1]` is the last element of `a_flat`:

In [7]:
print(a_flat[-1])

12


A negative step can be used to reverse the array:

In [8]:
a_reverse = a_flat[::-1]
print(a_reverse)
c = a_reverse[-3:]
b = np.copy(a_reverse[-3:-1])
a_reverse[-3:-1]=0
#b = 0
print(b)
print(c)

[12 11 10  9  8  7  6  5  4  3  2  1]
[3 2]
[0 0 1]


**REMINDER: A slice of an array (or simply the "whole" slice that is obtained by assigning an array to a new variable name) is a view into the same data, so modifying it will modify the original array**:

In [9]:
xx = np.array([1,2]) # First array
print("xx =",xx) 
yy = xx              # Slice, in this case a full slice, i.e. equality
print("yy =",yy)
xx[0] = 3            # First array is modified, also yy is modified

print("\nxx =",xx)
print("yy =",yy) 

xx = [1 2]
yy = [1 2]

xx = [3 2]
yy = [3 2]


If you want to avoid this behaviour you need to create a new numpy array with the slice of the previos array: 

In [10]:
xx = np.array([1,2])
print("xx =",xx)
yy = np.copy(xx)
print("yy =",yy)
xx[0] = 3

print("\nxx =",xx)
print("yy =",yy) 

xx = [1 2]
yy = [1 2]

xx = [3 2]
yy = [1 2]


The same holds for the `ravel` function: use `flatten` instead of `ravel` to create a new copy of the array.

### Array indexing: boolean

In [11]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a.shape)

bool_idx = (a >= 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

bool_idx2 = (a < 5)
            
print(bool_idx,"\n")
print(bool_idx2,"\n")

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[False  True]
 [ True  True]
 [ True  True]] 

[[ True  True]
 [ True  True]
 [False False]] 



In [12]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx],"\n")  

# We can do all of the above in a single concise statement:
print(a[a >= 2],"\n")

print(a[bool_idx & bool_idx2])
print(a[(a >=2) & (a < 5)])

[2 3 4 5 6] 

[2 3 4 5 6] 

[2 3 4]
[2 3 4]


## Exercise 3: slicing
[10 min]

Create an array containing the first 10 even numbers. Then:
- print all those which are greater than 5, using slicing;
- add 1 to all the elements that are smaller than 5, and print the result in reverse order;
- create a new array which contains only the odd entries of the above array, and print it;

## Array math

Basic mathematical functions operate elementwise on arrays, i.e. operate on each element separately (**element-wise operation**). We can perform scalar multiplication:

In [13]:
y = np.array([1,2,3])
alpha = 3.5

print(alpha*y)

[ 3.5  7.  10.5]


or apply functions to arrays:

In [14]:
x2 = np.array([1,4,9,25])
x = np.sqrt(x2) # Compute the square root
x3 = x**3       # Compute the cube
print(x)
print(x3)

[1. 2. 3. 5.]
[  1.   8.  27. 125.]


Mathematical functions are available both as operator and as functions in the numpy module:

In [15]:
print(x + x2)
print(np.add(x, x2))

[ 2.  6. 12. 30.]
[ 2.  6. 12. 30.]


In [16]:
print(x * x2)
print(np.multiply(x, x2))
print(np.dot(x,x2))

[  1.   8.  27. 125.]
[  1.   8.  27. 125.]
161.0


Of course arrays must have the same shape:

In [17]:
y = np.array([1,2])
print(x*y)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [18]:
x = np.arange(1,5,1)
y = np.ones([8,4])
print(x)
print(y)
print(x*y)

[1 2 3 4]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


## Boolean arrays

Boolean arrays can be created using the usual comparison operators, such as `>` (greater), `<` (smaller), `==` (equal to) and `!=` (not equal to), and they can be combined using the bitwise operators `&` (and), `|` (or), and `~` (not):

In [19]:
a = np.arange(0,10,1)
print(a)

b = a<5
print(b)

c = (a>3)
print(b & c)

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[False False False False  True False False False False False]


Boolean arrays can be used to select elements in an array:


In [20]:
print(a[b])
print(a[b & c])

[0 1 2 3 4]
[4]


## Other types

In [21]:
a = np.array([1,2,3],dtype=int)
b = np.array(['a','b','c'],dtype=str)
print(a)
print(b)

[1 2 3]
['a' 'b' 'c']


## Some additional functions & further reference

Finally, Numpy provides many useful functions for performing computations on arrays, like sum, inner products and trasposition (see here for a complete list https://docs.scipy.org/doc/numpy/reference/routines.math.html ):

In [22]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

10
[4 6]
[3 7]


In [23]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))

219
219


In [24]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x,"\n")    
print(x.T)  # Transposition, i.e. switch between rows and columns

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Exercise 4: array operations
Define a function that takes two arrays as input, subtracts them and returns two different arrays, one with the resulting positive numbers, and the other with the negative ones (either can be empty). The two input arrays must have the same length: check that within the function.

# Random numbers with NumPy

In Astrophysics, for many application, it can happen that you need random numbers. NumPy provides us with useful tools to generate them. In several situations, you will need random numbers generated from a **uniform distribution** in the interval $[0,1)$. To generate them you just need to access the random package of NumPy, i.e. `np.random.some_method()`. Here and example:

In [25]:
import numpy as np # numpy import

rnd1 = np.random.random()
print(rnd1)

0.8721248645832305


The above function `random` called with no argument just generates a single random number drawn from the Uniform distribution in $[0,1)$. If you call the function with a single integer number N than N random numbers are generated in the form of a 1D numpy array. Finally, if you specify the shape (enclosed in **round `( )` or squared `[ ]` parentheses**, i.e. provide the shape with a Tuple or a list) of a multi-dimensional array, then you get a multi-dimensional array of the specified shape filled with uniform random numbers between 0 and 1

In [26]:
print(np.random.random(3))

print("\n")
print(np.random.random([3,3,4]))

[0.23009274 0.25822367 0.98021142]


[[[0.19122609 0.47548679 0.28742281 0.85136341]
  [0.43627587 0.04903618 0.51562441 0.09214554]
  [0.23907164 0.45642885 0.53765554 0.1365105 ]]

 [[0.86818656 0.71228042 0.78590423 0.90425398]
  [0.61445723 0.27305333 0.83766086 0.43030783]
  [0.93075437 0.48887089 0.42449337 0.84691763]]

 [[0.17139093 0.0303377  0.84705794 0.80244835]
  [0.35343495 0.00664403 0.96114177 0.62571781]
  [0.88786004 0.70925918 0.49344333 0.16739846]]]


Each time that you call the above functions, different random numbers are generated. If you need to generate always the same sequence you have to specify the **seed** of the random generator, i.e.:

In [27]:
np.random.seed(55)                 # explicit specification of the seed
print(np.random.random(3))
print("\n")
print(np.random.random((3,3,4)))

[0.09310829 0.97165592 0.48385998]


[[[0.2425227  0.53112383 0.28554424 0.86263038]
  [0.04110015 0.10834773 0.76716005 0.05142871]
  [0.77571654 0.00913894 0.61831211 0.81870933]]

 [[0.89858572 0.98561158 0.49674492 0.35231893]
  [0.86708499 0.39688175 0.64365722 0.02045331]
  [0.80808454 0.4296133  0.55854652 0.77911129]]

 [[0.40255712 0.90799492 0.64996961 0.72727223]
  [0.77956104 0.35072745 0.01965992 0.35855857]
  [0.30322545 0.91906199 0.25339693 0.24115477]]]


and this will always generate the same sequence.

NumPy has built-in methods to generate random numbers distributed according to many different known distributions, e.g. gaussian, poission, binomial etc. Here the full list https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html

## Exercise 5
Generate 10000 pseudo-random coordinates in a 4D cube, then use these samples to compute the volume of a 4D sphere by [Monte-Carlo integration](https://en.wikipedia.org/wiki/Monte_Carlo_integration).